### PR TITLE
Add all data of user for a specific month

### PR DESCRIPTION
**Pull request by ramazanoacar**

### CODE REVIEW

**Comment by ramazanoacar** [comment]
Here is an example csv file for the command: "/get-user-mohthly-data-to-csv username: berkingurcan date: 2024-07"
I used test data between 2024-07-10 and 2024-07-20. Therefore, resulting csv has only data for these days.
[user_monthly_data.csv](https://github.com/user-attachments/files/17338817/user_monthly_data.csv)

**Review by berkingurcan — COMMENTED** [review]
All other LGTM! Command is working well, code is good.

**Review by berkingurcan — CHANGES_REQUESTED** [review]
All other LGTM! Command is working well, code is good.

**Review by berkingurcan — APPROVED** [review]
Great work!

**Pull request merged**
